GET http://localhost:8080/api/docinfo/getdocinfo HTTP/1.1

# POST http://localhost:8080/api/docinfo/adddocinfo HTTP/1.1
# Content-Type: application/json

# {
#   "doctorId": "1234",
#   "name": "Dr. John Doe",
#   "gender": "Male",
#   "location": "City Hospital",
#   "description": "Experienced doctor specialized in Cardiology",
#   "specialization": "Cardiology",
#   "charge_per_hour": 150
# }
